scratcher:                  edit.delete_word()
nope: edit.undo(
disk: edit.save()
disk all: edit.save_all()
tug: edit.left()
drain: edit.word_left()
push: edit.right()
step: edit.word_right()
north: edit.up()
south: edit.down()
head: edit.line_start()
tail: edit.line_end()
drink: edit.line_insert_up()
pour: edit.line_insert_down()